name: Android Debug Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get LTW
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          repo: MojoLauncher/LTW
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Full Debug
        run: |
          gradle :app_pojavlauncher:assembleFullDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: quattro-debug
          path: app_pojavlauncher/build/outputs/**/*.apk
